In [2]:
import numpy as np

In [3]:
array_1 = np.array([1,2,3,4,5])
array_1

array([1, 2, 3, 4, 5])

In [4]:
array_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
array_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [11]:
array_3d.dtype

dtype('int32')

In [17]:
array_1[-1]

5

In [18]:
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
array_2d[:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [30]:
num = [n for n in range(1,17)]
arr1 = np.array(num)
arr1
arr1.shape

(16,)

In [33]:
arr1_reshaped = arr1.reshape(4,4)
arr1_reshaped

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [34]:
arr1_flatten = arr1_reshaped.flatten()

In [35]:
arr1_flatten

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [47]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
total = a + b

In [37]:
total

array([5, 7, 9])

In [45]:
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
d = np.array([1, 0, 1])

broadcasted_sum = c + d
broadcasted_sum

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10]])

In [48]:
sqrt_array = np.sqrt(arr1_flatten)
print("Square root:", sqrt_array)

Square root: [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766 3.31662479 3.46410162
 3.60555128 3.74165739 3.87298335 4.        ]


In [49]:
dot_product = np.dot(a, b)
print("Dot product:", dot_product)

Dot product: 32


In [50]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
cross_product = np.cross(a, b)
print("Cross product:", cross_product)

Cross product: [-3  6 -3]


In [51]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
transpose = matrix.T
transpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [54]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])
concatenated_rows = np.concatenate((array1, array2), axis=0)

In [56]:
array1

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
array2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [55]:
concatenated_rows

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [58]:
concatenated_cols = np.concatenate((array1, array2), axis=1)

In [60]:
concatenated_cols

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [62]:
hsplit_arrays = np.hsplit(array1, 3)
print("Horizontal split:", hsplit_arrays)

Horizontal split: [array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [63]:
vsplit_arrays = np.vsplit(array1, 2)
print("Vertical split:", vsplit_arrays)

Vertical split: [array([[1, 2, 3]]), array([[4, 5, 6]])]


In [64]:
array = np.array([1, 2, 3, 4, 5])
inserted = np.insert(array, 2, [10, 20, 30])

In [65]:
array

array([1, 2, 3, 4, 5])

In [67]:
deleted = np.delete(array, [1, 2])
deleted

array([1, 4, 5])

In [68]:

data = np.array([4, 5, 1, 2, 7, 2, 6, 3, 5, 2])

In [71]:
mean = np.mean(data)
mean

3.7

In [73]:
median = np.median(data)
median

3.5

In [75]:
variance = np.var(data)
print("Variance:", variance)  # 3.61

Variance: 3.6100000000000003


In [78]:
std_dev = np.std(data)
print("Standard Deviation:", std_dev) 

Standard Deviation: 1.9000000000000001


In [80]:
print(1.9000000000000001**2)

3.6100000000000003


In [82]:
array_sum = np.sum(data)
print("Sum:", array_sum)  

Sum: 37


In [84]:
array_max = np.max(data)
print("Max:", array_max) 

Max: 7


In [86]:
array_min = np.min(data)
print("Min:", array_min)  # 1

Min: 1


In [88]:
array_argmax = np.argmax(data)
print("Argmax:", array_argmax)

Argmax: 4


In [133]:
np.random.seed(42)

random_array = np.random.rand()
print("Random array with seed 42:", random_array)

Random array with seed 42: 0.3745401188473625
